function geompack_test01 ( )

%*****************************************************************************80
%
%% TEST01 tests POINTS_DELAUNAY_NAIVE_2D.
%
%  Diagram:
%
%   !....3&11....
%   !............
%   !............
%   X..9.........
%   !.....5......
%   !...........6
%   !.4.2...10...
%   !.....8...12.
%   V............
%   !..7.........
%   !......1.....
%   !............
%   !............
%   !----V----X--
%
%  Licensing:
%
%    This code is distributed under the GNU LGPL license.
%
%  Modified:
%
%    14 February 2003
%
%  Author:
%
%    John Burkardt
%
  ndim = 2;
  n = 12;

  p = [ ...
     7.0,  3.0; ...
     4.0,  7.0; ...
     5.0, 13.0; ...
     2.0,  7.0; ...
     6.0,  9.0; ...
    12.0,  8.0; ...
     3.0,  4.0; ...
     6.0,  6.0; ...
     3.0, 10.0; ...
     8.0,  7.0; ...
     5.0, 13.0; ...
    10.0,  6.0 ]';

  fprintf ( 1, '\n' );
  fprintf ( 1, 'TEST01\n' );
  fprintf ( 1, '  POINTS_DELAUNAY_NAIVE_2D computes the Delaunay\n' );
  fprintf ( 1, '  triangulation of a set of points.\n' );

  r8mat_transpose_print ( ndim, n, p, '  The points:' );

  [ ntri, tri ] = points_delaunay_naive_2d ( n, p );

  i4mat_transpose_print ( 3, ntri, tri, '  The Delaunay triangles:' );

  return
end
