function [ node_coord, node_att, node_marker ] = triangle_node_data_example ( ...
  node_num, node_dim, node_att_num, node_marker_num )

%*****************************************************************************80
%
%% TRIANGLE_NODE_DATA_EXAMPLE returns the node information for the example.
%
%  Licensing:
%
%    This code is distributed under the GNU LGPL license.
%
%  Modified:
%
%    11 October 2014
%
%  Author:
%
%    John Burkardt
%
%  Parameters:
%
%    Input, integer NODE_NUM, the number of nodes.
%
%    Input, integer NODE_DIM, the spatial dimension.
%
%    Input, integer NODE_ATT_NUM, number of node attributes 
%    listed on each node record.
%
%    Input, integer NODE_MARKER_NUM, 1 if every node record 
%    includes a final boundary marker value.
%
%    Output, real NODE_COORD(NODE_DIM,NODE_NUM), the nodal 
%    coordinates.
%
%    Output, real NODE_ATT(NODE_ATT_NUM,NODE_NUM), the nodal 
%    attributes.
%
%    Output, integer NODE_MARKER(NODE_MARKER_NUM,NODE_NUM), 
%    the node markers.
%
  node_coord = [ ...
    0.0, 0.0; ...
    1.0, 0.0; ...
    2.0, 0.0; ...
    3.0, 0.0; ...
    4.0, 0.0; ...
    0.0, 1.0; ...
    1.0, 1.0; ...
    2.0, 1.0; ...
    3.0, 1.0; ...
    4.0, 1.0; ...
    0.0, 2.0; ...
    1.0, 2.0; ...
    2.0, 2.0; ...
    3.0, 2.0; ...
    4.0, 2.0; ...
    0.0, 3.0; ...
    1.0, 3.0; ...
    2.0, 3.0; ...
    0.0, 4.0; ...
    1.0, 4.0; ...
    2.0, 4.0 ]';

  node_att = [];

  node_marker = [ ...
    1; 1; 1; 1; 1; 1; 0; 0; 0; 1; ...
    1; 0; 0; 1; 1; 1; 0; 1; 1; 1; ...
    1 ]';

  return
end
