function sandia_sgmgg_test01 ( )

%*****************************************************************************80
%
%% SANDIA_SGMGG_TEST01 demonstrates the naive coefficient calculations.
%
%  Licensing:
%
%    This code is distributed under the GNU LGPL license.
%
%  Modified:
%
%    23 August 2011
%
%  Author:
%
%    John Burkardt
%
  fprintf ( 1, '\n' );
  fprintf ( 1, 'SANDIA_SGMGG_TEST01:\n' );
  fprintf ( 1, '  Demonstrate naive coefficient calculations.\n' );
%
%  Isotropic grid in 2D.
%
  fprintf ( 1, '\n' );
  fprintf ( 1, '  1) Isotropic grid in 2D\n' );

  dim_num = 2;
  point_num = 7;

  sparse_index = [ ...
    0, 2; ...
    0, 3; ...
    1, 1; ...
    1, 2; ...
    2, 0; ...
    2, 1; ...
    3, 0 ]';

  sandia_sgmgg_coef_naive_test ( dim_num, point_num, sparse_index );
%
%  Isotropic grid in 3D.
%
  fprintf ( 1, '\n' );
  fprintf ( 1, '  2) Isotropic grid in 3D\n' );

  dim_num = 3;
  point_num = 19;

  sparse_index = [ ...
    0, 1, 0; ...
    0, 2, 0; ...
    0, 3, 0; ...
    1, 0, 0; ...
    1, 1, 0; ...
    1, 2, 0; ...
    2, 0, 0; ...
    2, 1, 0; ...
    3, 0, 0; ...
    0, 0, 1; ...
    0, 1, 1; ...
    0, 2, 1; ...
    1, 0, 1; ...
    1, 1, 1; ...
    2, 0, 1; ...
    0, 0, 2; ...
    0, 1, 2; ...
    1, 0, 2; ...
    0, 0, 3 ]';

  sandia_sgmgg_coef_naive_test ( dim_num, point_num, sparse_index );
%
%  Anisotropic grid in 2D.
%
  fprintf ( 1, '\n' );
  fprintf ( 1, '  3) Anisotropic grid in 2D\n' );

  dim_num = 2;
  point_num = 8;

  sparse_index = [ ...
    0, 2; ...
    1, 1; ...
    1, 2; ...
    2, 1; ...
    3, 0; ...
    3, 1; ...
    4, 0; ...
    5, 0 ]';

  sandia_sgmgg_coef_naive_test ( dim_num, point_num, sparse_index );
%
%  Generalized grid in 2D.
%
  fprintf ( 1, '\n' );
  fprintf ( 1, '  4) Generalized grid in 2D\n' );

  dim_num = 2;
  point_num = 8;

  sparse_index = [ ...
    0, 0; ...
    0, 1; ...
    0, 2; ...
    0, 3; ...
    1, 0; ...
    1, 1; ...
    2, 0; ...
    3, 0 ]';

  sandia_sgmgg_coef_naive_test ( dim_num, point_num, sparse_index );

  return
end
