function gl_grids_minmax_display ( )

%*****************************************************************************80
%
%% GL_GRIDS_MINMAX_DISPLAY displays grids generated by GL_GRIDS_MINMAX.
%
%  Licensing:
%
%    This code is distributed under the GNU LGPL license.
%
%  Modified:
%
%    06 November 2006
%
%  Author:
%
%    John Burkardt
%
  fprintf ( 1, '\n' );
  timestamp ( );

  fprintf ( 1, '\n' );
  fprintf ( 1, 'GL_GRIDS_MINMAX_DISPLAY:\n' );
  fprintf ( 1, '  MATLAB version\n' );
  fprintf ( 1, '  Display the 2D Gauss-Legendre grids\n' );
  fprintf ( 1, '  generated by GL_GRIDS_MINMAX.\n' );

  dim_num = 2;
 
  while ( 1 )
%
%  Get user input.
%
    q_min = input ( 'Enter Q_MIN or RETURN to exit;' );
    
    if ( isempty ( q_min ) )
      break
    end

    if ( q_min < dim_num )
      fprintf ( 1, '\n' );
      fprintf ( 1, '  We require 2 = DIM_NUM <= Q_MIN\n' );
      continue
    end

    q_max = input ( 'Enter Q_MAX or RETURN to exit;' );
    
    if ( isempty ( q_max ) )
      break
    end
    
    if ( q_max < q_min )
      fprintf ( 1, '\n' );
      fprintf ( 1, '  We require Q_MIN <= Q_MAX!\n' );
      continue
    end
%
%  Compute data.
%
    [ grid_num, point_num ] = gl_grids_minmax_size ( dim_num, q_min, q_max );
    
    [ grid_order, grid_point ] = gl_grids_minmax ( dim_num, q_min, q_max, ...
      grid_num, point_num );

    clf
%
%  We have to name the axes in order to control the grid.
%
    axes_handle = axes;
%
%  Plot the points.
%
    handle = scatter ( grid_point(1,:), grid_point(2,:), 'filled' );
%
%  Force the plotting region to be square, not rectangular.
%
    axis square
%
%  Request grid lines.
%
    grid on
%
%  Specify the location of the grid lines, and suppress labeling.
%
    set ( axes_handle, 'xtick', [ -1, -.75, -.5, -.25, 0, .25, .50, .75, 1] );
    set ( axes_handle, 'xticklabel', [] );
    set ( axes_handle, 'ytick', [ -1, -.75, -.5, -.25, 0, .25, .50, .75, 1] );
    set ( axes_handle, 'yticklabel', [] );
%
%  Make the plotting region slightly bigger than the data.
%
    axis ( [ -1.1, 1.1, -1.1, 1.1 ] )
%
%  Title
%
    s = sprintf ( '%d <= Q <= %d', q_min, q_max );
    title ( s );
    
  end

  fprintf ( 1, '\n' );
  fprintf ( 1, 'GL_GRIDS_MINMAX_DISPLAY:\n' );
  fprintf ( 1, '  Normal end of execution.\n' );

  fprintf ( 1, '\n' );
  timestamp ( );

  return
end
