function gl_levels_minmax_display ( )

%*****************************************************************************80
%
%% GL_LEVELS_MINMAX_DISPLAY displays grids generated by GL_LEVELS_MINMAX.
%
%  Licensing:
%
%    This code is distributed under the GNU LGPL license.
%
%  Modified:
%
%    05 November 2006
%
%  Author:
%
%    John Burkardt
%
  fprintf ( 1, '\n' );
  timestamp ( );

  fprintf ( 1, '\n' );
  fprintf ( 1, 'GL_LEVELS_MINMAX_DISPLAY:\n' );
  fprintf ( 1, '  Display the 2D Gauss-Legendre grids\n' );
  fprintf ( 1, '  generated by GL_LEVELS_MINMAX.\n' );

  dim_num = 2;
 
  while ( 1 )
%
%  Get user input.
%
    level_min = input ( 'Enter LEVEL_MIN or RETURN to exit;' );
    
    if ( isempty ( level_min ) )
      break
    end

    if ( level_min < 0 )
      fprintf ( 1, '\n' );
      fprintf ( 1, '  We require 0 <= LEVEL_MIN\n' );
      continue
    end

    level_max = input ( 'Enter LEVEL_MAX or RETURN to exit;' );
    
    if ( isempty ( level_max ) )
      break
    end
    
    if ( level_max < level_min )
      fprintf ( 1, '\n' );
      fprintf ( 1, '  We require LEVEL_MIN <= LEVEL_MAX!\n' );
      continue
    end
%
%  Compute data.
%
    [ grid_num, point_num ] = gl_levels_minmax_size ( dim_num, ...
      level_min, level_max );
    
    [ grid_level, grid_order, grid_point ] = gl_levels_minmax ( dim_num, ...
      level_min, level_max,  grid_num, point_num );

    clf
%
%  We have to name the axes in order to control the grid.
%
    axes_handle = axes;
%
%  Plot the points.
%
    handle = scatter ( grid_point(1,:), grid_point(2,:), 'filled' );
%
%  Force the plotting region to be square, not rectangular.
%
    axis square
%
%  Request grid lines.
%
    grid on
%
%  Specify the location of the grid lines, and suppress labeling.
%
    set ( axes_handle, 'xtick', [ -1, -.75, -.5, -.25, 0, .25, .50, .75, 1] );
    set ( axes_handle, 'xticklabel', [] );
    set ( axes_handle, 'ytick', [ -1, -.75, -.5, -.25, 0, .25, .50, .75, 1] );
    set ( axes_handle, 'yticklabel', [] );
%
%  Make the plotting region slightly bigger than the data.
%
    axis ( [ -1.1, 1.1, -1.1, 1.1 ] )
%
%  Title
%
    s = sprintf ( '%d <= LEVEL <= %d', level_min, level_max );
    title ( s );
    
  end

  fprintf ( 1, '\n' );
  fprintf ( 1, 'GL_LEVELS_MINMAX_DISPLAY:\n' );
  fprintf ( 1, '  Normal end of execution.\n' );

  fprintf ( 1, '\n' );
  timestamp ( );

  return
end
